# Generated by Django 3.1.2 on 2020-10-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20201028_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='default@email.email', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
